// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// RMA_sum
Rcpp::List RMA_sum(arma::mat x2, Rcpp::List probesets, CharacterVector order, CharacterVector colnames);
RcppExport SEXP hemaClass_RMA_sum(SEXP x2SEXP, SEXP probesetsSEXP, SEXP orderSEXP, SEXP colnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type probesets(probesetsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type order(orderSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colnames(colnamesSEXP);
    __result = Rcpp::wrap(RMA_sum(x2, probesets, order, colnames));
    return __result;
END_RCPP
}
// RMA_norm
Rcpp::List RMA_norm(const NumericMatrix x2, arma::vec quantile2, int generateQuan);
RcppExport SEXP hemaClass_RMA_norm(SEXP x2SEXP, SEXP quantile2SEXP, SEXP generateQuanSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type quantile2(quantile2SEXP);
    Rcpp::traits::input_parameter< int >::type generateQuan(generateQuanSEXP);
    __result = Rcpp::wrap(RMA_norm(x2, quantile2, generateQuan));
    return __result;
END_RCPP
}
// userRMA
Rcpp::List userRMA(const NumericMatrix x2, Rcpp::List probesets, CharacterVector colnames, NumericVector quantile, NumericVector alpha);
RcppExport SEXP hemaClass_userRMA(SEXP x2SEXP, SEXP probesetsSEXP, SEXP colnamesSEXP, SEXP quantileSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type probesets(probesetsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type colnames(colnamesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(userRMA(x2, probesets, colnames, quantile, alpha));
    return __result;
END_RCPP
}
