# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RMA_sum <- function(x2, probesets, order, colnames) {
    .Call('hemaClass_RMA_sum', PACKAGE = 'hemaClass', x2, probesets, order, colnames)
}

RMA_norm <- function(x_usr, quantile_usr, generateQuan) {
    .Call('hemaClass_RMA_norm', PACKAGE = 'hemaClass', x_usr, quantile_usr, generateQuan)
}

userRMA <- function(x2, probesets, colnames, quantile, alpha) {
    .Call('hemaClass_userRMA', PACKAGE = 'hemaClass', x2, probesets, colnames, quantile, alpha)
}

